name: llm_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - datasets
  - transformers
  - tqdm
  - matplotlib
  - tensorboard
  - accelerate
  - safetensors
  - sentencepiece
  - pip
  - pip:
      - "--index-url https://download.pytorch.org/whl/cu118"
      - torch==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - torchaudio==2.6.0+cu118