import torch
from .utils_simulation import make_padded_batch_from_token_lists
from .utils_parsing import is_correct


@torch.inference_mode()
def rollout_answer_reward(
    model,
    tokenizer,
    token_lists_after_action,
    golds,
    max_rollout_tokens=64,
    rollout_gamma=0.97,
    eos_token_id=None,
    do_sample=False,
    temperature=1.0,
    top_k=None,
    device="cpu",
):
    """
    Short rollout reward.

    Given contexts that already include the chosen next token a_t,
    let the frozen LM generate up to max_rollout_tokens more tokens.
    Reward is higher when the correct answer appears earlier.

    Returns:
        rewards: torch.FloatTensor [B]
        hit_steps: list[int | None]
            0 means answer was already present immediately after a_t.
            1 means answer appeared after 1 rollout token.
            None means answer did not appear during rollout.
    """

    if eos_token_id is None:
        eos_token_id = tokenizer.eos_token_id

    # First check whether the answer is already present after taking a_t.
    rewards = []
    hit_steps = []

    already_done = []
    for ids, gold in zip(token_lists_after_action, golds):
        text = tokenizer.decode(ids, skip_special_tokens=True)
        hit = is_correct(text, gold)

        already_done.append(hit)
        if hit:
            rewards.append(1.0)
            hit_steps.append(0)
        else:
            rewards.append(0.0)
            hit_steps.append(None)

    # If all are already correct, no need to rollout.
    if all(already_done):
        return torch.tensor(rewards, dtype=torch.float32, device=device), hit_steps

    batch = make_padded_batch_from_token_lists(
        token_lists=token_lists_after_action,
        pad_token_id=tokenizer.pad_token_id,
        device=device,
        max_context_len=None,
    )

    prompt_len = batch["input_ids"].shape[1]

    gen_kwargs = dict(
        input_ids=batch["input_ids"],
        attention_mask=batch["attention_mask"],
        max_new_tokens=max_rollout_tokens,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=eos_token_id,
        do_sample=do_sample,
    )

    if do_sample:
        gen_kwargs["temperature"] = temperature
        if top_k is not None:
            gen_kwargs["top_k"] = top_k

    outputs = model.generate(**gen_kwargs)

    # New tokens generated by the rollout.
    new_tokens = outputs[:, prompt_len:]

    B = len(token_lists_after_action)

    for i in range(B):
        if already_done[i]:
            continue

        base_ids = token_lists_after_action[i]
        gold = golds[i]

        # Scan prefixes of the rollout to find the earliest answer.
        for step in range(1, new_tokens.shape[1] + 1):
            rollout_ids = new_tokens[i, :step].tolist()

            # Optional: stop scanning after EOS.
            if eos_token_id is not None and eos_token_id in rollout_ids:
                eos_pos = rollout_ids.index(eos_token_id)
                rollout_ids = rollout_ids[: eos_pos + 1]

            candidate_ids = base_ids + rollout_ids
            candidate_text = tokenizer.decode(candidate_ids, skip_special_tokens=True)

            if is_correct(candidate_text, gold):
                hit_steps[i] = step

                # Discounted reward: earlier hit => larger reward.
                rewards[i] = rollout_gamma ** step
                break

            if eos_token_id is not None and eos_token_id in rollout_ids:
                break

    rewards = torch.tensor(rewards, dtype=torch.float32, device=device)
    return rewards, hit_steps